import type { Metadata } from "next";

/**
 * Single source of truth for everything a search engine or AI crawler reads.
 *
 * Rules for this file:
 *  - Never state a number, fee or capability here that the product cannot back up.
 *    Fake stats in metadata are a manual-action risk and they destroy the trust the
 *    product exists to create.
 *  - Every keyword in KEYWORD_CLUSTERS must be mapped to a page that genuinely
 *    answers it. A keyword with no page behind it is a promise to a crawler we
 *    cannot keep.
 */

const RAW_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://chatcart.shop";

export const SITE = {
  name: "ChatCart",
  url: RAW_SITE_URL.replace(/\/+$/, ""),
  /** Nigerian English locale — this marketplace only serves Nigeria today. */
  locale: "en_NG",
  lang: "en-NG",
  country: "Nigeria",
  countryCode: "NG",
  tagline: "Chat, agree the price, pay into escrow.",
  shortDescription:
    "ChatCart is a social commerce marketplace: discover products in a video feed, agree the price in chat, and pay into escrow.",
  longDescription:
    "ChatCart is a chat-first social commerce marketplace for Nigeria. Buyers discover local products in a full-screen video feed, message sellers with the exact item already attached, negotiate a price with offers and counter-offers, and pay into escrow that only releases once the order is received.",
  email: "hello@chatcart.app",
  supportEmail: "support@chatcart.app",
  legalEmail: "legal@chatcart.app",
  privacyEmail: "privacy@chatcart.app",
  twitter: "@chatcartapp",
  /** Money model facts that appear in copy must come from here so they can't drift. */
  facts: {
    sellerAcceptWindowHours: 24,
    autoReleaseAfterShipmentHours: 48,
    offerExpiryHours: 72,
    minimumPayoutNgn: 5000,
    payoutProcessingBusinessDays: 3,
  },
} as const;

export function absoluteUrl(path = "/"): string {
  const clean = path.startsWith("/") ? path : `/${path}`;
  return clean === "/" ? SITE.url : `${SITE.url}${clean.replace(/\/+$/, "")}`;
}

/**
 * The shared social preview card, generated by the app repository's
 * scripts/generate-brand-assets.mjs and served from `public/`.
 *
 * This is referenced explicitly rather than left to Next's `opengraph-image`
 * file convention. That convention only applies to the segment the file sits
 * in, so the root `app/opengraph-image.png` covered the homepage but left every
 * content page — /escrow, /glossary/*, /compare/* — with no `og:image` at all,
 * meaning links to them shared with no picture. One stable URL referenced from
 * the metadata builders puts a card on every page.
 */
export const SOCIAL_IMAGE = {
  url: `${SITE.url}/opengraph-image.png`,
  width: 1200,
  height: 630,
  alt: `${SITE.name} — ${SITE.tagline}`,
} as const;

/* ------------------------------------------------------------------ *
 * Metadata
 * ------------------------------------------------------------------ */

export type BuildMetadataInput = {
  /** Page title WITHOUT the brand — the root template appends "| ChatCart". */
  title: string;
  titleAbsolute?: boolean;
  description: string;
  /** Path beginning with "/". Used for the canonical URL. */
  path: string;
  keywords?: string[];
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  noIndex?: boolean;
};

export function buildMetadata({
  title,
  titleAbsolute,
  description,
  path,
  keywords,
  type = "website",
  publishedTime,
  modifiedTime,
  noIndex,
}: BuildMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const socialTitle = `${title} | ${SITE.name}`;

  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      type,
      url,
      siteName: SITE.name,
      title: socialTitle,
      description,
      locale: SITE.locale,
      images: [SOCIAL_IMAGE],
      ...(type === "article" ? { publishedTime, modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      site: SITE.twitter,
      images: [SOCIAL_IMAGE.url],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}

/* ------------------------------------------------------------------ *
 * Keyword registry
 *
 * Each cluster is a distinct search intent. The `page` is the page that
 * actually answers it — this is what the sitemap and internal links are
 * built from, so the map is executable, not decorative.
 * ------------------------------------------------------------------ */

export type KeywordCluster = {
  id: string;
  label: string;
  /** Path of the page that answers this cluster. */
  page: string;
  terms: string[];
};

export const KEYWORD_CLUSTERS: KeywordCluster[] = [
  {
    id: "chat-commerce",
    label: "Chat-first commerce",
    page: "/chat",
    terms: [
      "chat for marketplace",
      "marketplace chat app",
      "chat to buy app",
      "in-app chat marketplace",
      "buyer and seller chat app",
      "message seller before buying",
      "conversational commerce Nigeria",
      "chat commerce",
      "instant messaging for online shopping",
      "DM to buy",
    ],
  },
  {
    id: "escrow",
    label: "Escrow & safe payment",
    page: "/escrow",
    terms: [
      "escrow payment Nigeria",
      "escrow app Nigeria",
      "escrow marketplace",
      "what is escrow payment",
      "how escrow works when buying online",
      "safe online payment Nigeria",
      "buyer protection Nigeria",
      "secure payment for online sellers",
      "online payment protection",
      "money held until delivery",
      "escrow account for online shopping",
      "release payment after delivery",
    ],
  },
  {
    id: "offers",
    label: "Offers & price negotiation",
    page: "/offers",
    terms: [
      "make an offer marketplace",
      "price negotiation app",
      "negotiate price online",
      "haggle online shopping",
      "send an offer app",
      "counter offer marketplace",
      "best offer app Nigeria",
      "agree a price in chat",
    ],
  },
  {
    id: "social-commerce",
    label: "Social & video commerce",
    page: "/social-commerce",
    terms: [
      "social commerce Nigeria",
      "social commerce app",
      "video shopping app",
      "reels shopping",
      "shoppable video",
      "short video commerce",
      "creator commerce Nigeria",
      "product video feed",
      "TikTok shop alternative Nigeria",
      "Instagram shop alternative",
    ],
  },
  {
    id: "marketplace",
    label: "Marketplace & classifieds",
    page: "/",
    terms: [
      "online marketplace Nigeria",
      "buy and sell online Nigeria",
      "online shopping app Nigeria",
      "local online market",
      "WhatsApp business alternative",
      "sell on Instagram Nigeria",
      "online store without a website",
    ],
  },
  {
    id: "sellers",
    label: "For sellers",
    page: "/for-sellers",
    terms: [
      "sell online in Nigeria",
      "seller dashboard app",
      "payout app for online sellers",
      "manage online orders",
      "online store for small business Nigeria",
      "get paid online Nigeria",
      "sell fashion online Nigeria",
    ],
  },
  {
    id: "buyers",
    label: "For buyers",
    page: "/for-buyers",
    terms: [
      "buy online safely Nigeria",
      "order tracking app",
      "delivery to your door Nigeria",
      "shop from local sellers",
      "online shopping without WhatsApp",
    ],
  },
  {
    id: "glossary",
    label: "Definitions",
    page: "/glossary",
    terms: [
      "what is social commerce",
      "what is conversational commerce",
      "what is an escrow account",
      "what is buyer protection",
      "what is a social commerce marketplace",
      "what is video commerce",
      "what is a payment gateway",
    ],
  },
  {
    id: "brand",
    label: "Brand",
    page: "/",
    terms: ["ChatCart", "ChatCart app", "ChatCart Nigeria", "ChatCart escrow"],
  },
];

export const ALL_KEYWORDS: string[] = Array.from(
  new Set(KEYWORD_CLUSTERS.flatMap((cluster) => cluster.terms))
);

/** Keywords that belong to one page, plus its cluster label terms. */
export function keywordsForPage(path: string): string[] {
  return KEYWORD_CLUSTERS.filter((cluster) => cluster.page === path).flatMap(
    (cluster) => cluster.terms
  );
}

/* ------------------------------------------------------------------ *
 * Structured data
 *
 * Deliberately absent: aggregateRating and review markup. The product has no
 * real ratings to report, and inventing them is both a Google spam violation
 * and the exact dishonesty the escrow model is meant to prevent.
 * ------------------------------------------------------------------ */

export type Schema = Record<string, unknown>;
export type Crumb = { name: string; path: string };

function stripSchema<T>(value: T): T {
  // Removes empty-string/undefined noise so we never emit meaningless keys.
  return JSON.parse(
    JSON.stringify(value, (_key, val) => (val === undefined || val === "" ? undefined : val))
  ) as T;
}

export function organizationSchema(): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${SITE.url}/#organization`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.shortDescription,
    email: SITE.email,
    logo: {
      "@type": "ImageObject",
      url: absoluteUrl("/favicon.ico"),
    },
    areaServed: {
      "@type": "Country",
      name: SITE.country,
    },
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "customer support",
        email: SITE.supportEmail,
        areaServed: SITE.countryCode,
        availableLanguage: ["en"],
      },
    ],
  });
}

export function webSiteSchema(): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE.url}/#website`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.shortDescription,
    inLanguage: SITE.lang,
    publisher: { "@id": `${SITE.url}/#organization` },
  });
}

export function softwareApplicationSchema(): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${SITE.url}/#app`,
    name: SITE.name,
    applicationCategory: "ShoppingApplication",
    applicationSubCategory: "Social commerce marketplace",
    operatingSystem: "Android, iOS",
    url: SITE.url,
    description: SITE.longDescription,
    inLanguage: SITE.lang,
    publisher: { "@id": `${SITE.url}/#organization` },
    areaServed: { "@type": "Country", name: SITE.country },
    featureList: [
      "Product video feed",
      "Buyer and seller chat with item context attached",
      "Price offers, counter-offers and acceptance",
      "Escrow payment released on delivery",
      "Seller order management and bank payouts",
      "In-app dispute resolution",
    ],
  });
}

export function webPageSchema({
  name,
  description,
  path,
  primaryImage,
}: {
  name: string;
  description: string;
  path: string;
  primaryImage?: string;
}): Schema {
  const url = absoluteUrl(path);
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${url}/#webpage`,
    url,
    name,
    description,
    inLanguage: SITE.lang,
    isPartOf: { "@id": `${SITE.url}/#website` },
    about: { "@id": `${SITE.url}/#app` },
    primaryImageOfPage: primaryImage,
  });
}

export function breadcrumbSchema(trail: Crumb[]): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  });
}

export function faqSchema(items: { q: string; a: string }[]): Schema | null {
  if (!items.length) return null;
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  });
}

export function itemListSchema({
  name,
  items,
}: {
  name: string;
  items: { name: string; path: string }[];
}): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      url: absoluteUrl(item.path),
    })),
  });
}

export function serviceSchema({
  name,
  description,
  path,
  serviceType,
}: {
  name: string;
  description: string;
  path: string;
  serviceType: string;
}): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${absoluteUrl(path)}/#service`,
    name,
    description,
    serviceType,
    url: absoluteUrl(path),
    provider: { "@id": `${SITE.url}/#organization` },
    areaServed: { "@type": "Country", name: SITE.country },
    availableChannel: {
      "@type": "ServiceChannel",
      serviceUrl: absoluteUrl(path),
      availableLanguage: { "@type": "Language", name: "English" },
    },
  });
}

export function definedTermSchema({
  term,
  definition,
  path,
}: {
  term: string;
  definition: string;
  path: string;
}): Schema {
  return stripSchema({
    "@context": "https://schema.org",
    "@type": "DefinedTerm",
    "@id": `${absoluteUrl(path)}/#term`,
    name: term,
    description: definition,
    inDefinedTermSet: {
      "@type": "DefinedTermSet",
      name: `${SITE.name} glossary`,
      url: absoluteUrl("/glossary"),
    },
    url: absoluteUrl(path),
  });
}
