import type { MetadataRoute } from "next";

import { SITE } from "@/lib/seo";

/**
 * Icons are generated by scripts/generate-brand-assets.mjs in the app
 * repository. The maskable entry declares `purpose: "maskable"` because its
 * glyph is drawn inside the safe zone; the `any` entry is the plain favicon
 * tile, the same mark the app launcher shows.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE.name} — ${SITE.tagline}`,
    short_name: SITE.name,
    description: SITE.shortDescription,
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#fbf8f2",
    theme_color: "#A67C52",
    lang: SITE.lang,
    dir: "ltr",
    categories: ["shopping", "business", "social"],
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
      },
      {
        src: "/icon.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/logo-maskable.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "maskable",
      },
      {
        src: "/favicon.ico",
        sizes: "48x48",
        type: "image/x-icon",
      },
    ],
  };
}
